//! Stage discovery.
//!
//! Every module in `src/stages/` — a `name.rs` file, or a `name/` directory
//! holding a `mod.rs` — is compiled and registered without being listed
//! anywhere. This script only *lists* files; it writes
//! `$OUT_DIR/stages_gen.rs`, which `src/stages/mod.rs` includes:
//!
//! ```ignore
//! #[path = "/abs/path/src/stages/blend.rs"]
//! pub mod blend;
//! pub fn register_all(reg: &mut crate::exec::Registry) { blend::register(reg); }
//! ```
//!
//! Each stage module must define `pub fn register(reg: &mut Registry)`; the
//! compiler reports a module that does not.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Names a stage module cannot take: Rust keywords (strict, reserved and
/// edition-2024 weak ones that break `mod x;`), plus the item the generated
/// file defines itself.
const RESERVED: &[&str] = &[
    "abstract",
    "as",
    "async",
    "await",
    "become",
    "box",
    "break",
    "const",
    "continue",
    "crate",
    "do",
    "dyn",
    "else",
    "enum",
    "extern",
    "false",
    "final",
    "fn",
    "for",
    "gen",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "macro",
    "match",
    "mod",
    "move",
    "mut",
    "override",
    "priv",
    "pub",
    "ref",
    "return",
    "self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "try",
    "type",
    "typeof",
    "unsafe",
    "unsized",
    "use",
    "virtual",
    "where",
    "while",
    "yield",
    "register_all",
];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let stages_dir = manifest.join("src").join("stages");
    // A directory path makes Cargo rescan everything under it, so adding or
    // deleting a stage file reruns this script.
    println!("cargo:rerun-if-changed=src/stages");
    println!("cargo:rerun-if-changed=build.rs");

    let modules = discover(&stages_dir);
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("stages_gen.rs");
    fs::write(&out, render(&modules)).unwrap_or_else(|e| panic!("writing {}: {e}", out.display()));
}

/// `(module name, source file)` for every stage module, sorted by name.
fn discover(dir: &Path) -> Vec<(String, PathBuf)> {
    let entries = fs::read_dir(dir).unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()));
    let mut modules = Vec::new();
    for entry in entries {
        let path = entry.unwrap().path();
        let file_name = path.file_name().unwrap().to_string_lossy().into_owned();
        let (name, source) = if path.is_dir() {
            let source = path.join("mod.rs");
            if !source.is_file() {
                continue; // not a module, e.g. a folder of shaders or assets
            }
            (file_name.clone(), source)
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
            if stem == "mod" {
                continue;
            }
            (stem, path)
        } else {
            continue; // README, rustfmt `.rs.bk` backups, ...
        };
        if let Err(why) = check_name(&name) {
            panic!("src/stages/{file_name}: {why}; rename it to a snake_case Rust identifier");
        }
        modules.push((name, source));
    }
    modules.sort();
    modules
}

fn check_name(name: &str) -> Result<(), String> {
    let mut chars = name.chars();
    let first_ok = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    if !first_ok || name == "_" || !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!("'{name}' is not a valid module name"));
    }
    if RESERVED.contains(&name) {
        return Err(format!("'{name}' is a reserved name"));
    }
    Ok(())
}

fn render(modules: &[(String, PathBuf)]) -> String {
    let mut s = String::from(
        "// @generated by build.rs from the contents of src/stages/. Do not edit.\n\n",
    );
    for (name, source) in modules {
        // `{:?}` emits a valid Rust string literal, escaping Windows backslashes.
        writeln!(
            s,
            "#[path = {:?}]\npub mod {name};",
            source.display().to_string()
        )
        .unwrap();
    }
    s.push_str("\n/// Register every stage module's node kinds. Generated by `build.rs`.\n");
    s.push_str("pub fn register_all(reg: &mut crate::exec::Registry) {\n");
    for (name, _) in modules {
        writeln!(s, "    {name}::register(reg);").unwrap();
    }
    s.push_str("}\n");
    s
}
